# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectoralListSeatAssignment',
            fields=[
                ('electorallistseat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ElectoralListSeat')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('seats', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='electoral_list_seats', to='api.ElectoralList')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('api.electorallistseat', models.Model),
        ),
        migrations.RemoveField(
            model_name='electorallistseat',
            name='electoral_list',
        ),
        migrations.AddField(
            model_name='electorallistseat',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
    ]
