# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_electorallist_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollResultLink',
            fields=[
                ('pollresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.PollResult')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('seats', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_results', to='api.Poll')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('api.pollresult', models.Model),
        ),
    ]
