# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pollresultlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollresultlink',
            old_name='seats',
            new_name='poll',
        ),
    ]
