# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161024_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
