# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_party_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='extra_seats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
