# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 10:32
from __future__ import unicode_literals

from django.db import migrations

def sitesettings(apps, schema_editor):
    BaseTemplate = apps.get_model('core', 'BaseTemplate')
    SiteSettings = apps.get_model('core', 'GeneralSiteSettings')
    Site = apps.get_model('wagtailcore', 'Site')

    template = BaseTemplate.objects.create(
        title='election_api base template',
        filename='election_api_base.html',
    )
    settings = SiteSettings.objects.create(
        site=Site.objects.get(is_default_site=True),
        base_template=template,
        template_dir='election_api'
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(sitesettings)
    ]
